es6 imports / commonjs require
ConnecMent/bank pull request #19
Opened 2024-07-02 16:09 UTC by SeyedMojtaba1

related #5

2024-07-20 16:38 UTC, mkermani144 requested changes

2024-07-20 16:38 UTC, mkermani144 commented on Seyed/commonjs/ESA/package.json
> +    "module": "^1.2.5"
What's this? Probably a mistake? 🤔

2024-07-20 16:38 UTC, mkermani144 commented on Seyed/commonjs/ESA/.gitignore
> +node_modules/
Please note that it's not _ESA_, but _ESM_ (or **E**CMA**S**cript **M**odules).

2024-07-20 16:38 UTC, mkermani144 commented on Seyed/commonjs/commonjs/isNil.cjs
> +module.exports = {isNil};
While default and named exports are mostly ESM concepts, this is not a so called default export. You can directly export the `isNil` itself without wrapping it in an object.

2024-07-20 16:38 UTC, mkermani144 commented on Seyed/commonjs/commonjs/package.json
> +    "module": "^1.2.5"
Same here.

2024-07-25 18:23 UTC, SeyedMojtaba1 commented on Seyed/commonjs/ESA/package.json
> +    "module": "^1.2.5"
I fixed it. It's my mistake.

2024-07-25 18:23 UTC, SeyedMojtaba1 commented on Seyed/commonjs/ESA/.gitignore
> +node_modules/
Sure

2024-07-25 18:25 UTC, SeyedMojtaba1 commented on Seyed/commonjs/commonjs/isNil.cjs
> +module.exports = {isNil};
Okay, I understood.

2024-07-25 18:25 UTC, SeyedMojtaba1 commented on Seyed/commonjs/commonjs/package.json
> +    "module": "^1.2.5"
I fixed it.

2024-07-28 07:44 UTC, mkermani144 approved these changes

2024-07-28 07:44 UTC, merged