writing TS functions
ConnecMent/bank pull request #20
Opened 2024-07-15 11:09 UTC by SeyedMojtaba1

related #6

2024-07-17 06:30 UTC, fatemeh-ra requested changes
Please fix the comments

2024-07-17 06:30 UTC, fatemeh-ra commented on Seyed/TS syntax/.gitignore
> +tsconfig.json
you should NOT put `package.json`, `package-lock.json` and `tsconfig.json` in .gitignore

2024-07-17 06:30 UTC, fatemeh-ra commented on Seyed/TS syntax/syntax.ts
> +    Fname : string,
use camelCase format for variable names, it should be fName or firstName

2024-07-17 06:30 UTC, fatemeh-ra commented on Seyed/TS syntax/syntax.ts
> +        Fname : firstName,
you should capitalize the first letter

2024-07-17 06:30 UTC, fatemeh-ra commented on Seyed/TS syntax/syntax.ts
> +// callFuncNTimes(flipACoin, 5);
commented code are not allowed in the source code

2024-07-17 06:30 UTC, fatemeh-ra commented on Seyed/TS syntax/syntax.ts
> +function isNil(param?: number): boolean {
should return true with any falsy value including
```
0
-0
null
''
undefined
NaN
0n
false
```

2024-07-17 06:30 UTC, fatemeh-ra commented on Seyed/TS syntax/syntax.ts
> +    return email.includes("gmail");
including is not enough, it should have the correct format: xx@gmail.com

2024-07-17 06:30 UTC, fatemeh-ra commented on Seyed/TS syntax/syntax.ts
> +function duplicateArray<T>(array1: Array<T>, array2: Array<T>): boolean {
The issue description was not correct this function should have only one input array. and the return type was also incorrect.

2024-07-22 16:40 UTC, SeyedMojtaba1 commented on Seyed/TS syntax/syntax.ts
> +    Fname : string,
I fixed it.

2024-07-22 16:40 UTC, SeyedMojtaba1 commented on Seyed/TS syntax/syntax.ts
> +        Fname : firstName,
I did not understand it.

2024-07-22 16:40 UTC, SeyedMojtaba1 commented on Seyed/TS syntax/syntax.ts
> +// callFuncNTimes(flipACoin, 5);
I deleted it.

2024-07-22 16:40 UTC, SeyedMojtaba1 commented on Seyed/TS syntax/syntax.ts
> +function isNil(param?: number): boolean {
I fixed it.

2024-07-22 16:41 UTC, SeyedMojtaba1 commented on Seyed/TS syntax/syntax.ts
> +    return email.includes("gmail");
I fixed it.

2024-07-22 16:41 UTC, SeyedMojtaba1 commented on Seyed/TS syntax/syntax.ts
> +function duplicateArray<T>(array1: Array<T>, array2: Array<T>): boolean {
I fixed it.

2024-07-28 14:10 UTC, fatemeh-ra approved these changes

2024-07-28 14:10 UTC, merged