feat(): initial version of ts basics.
ConnecMent/bank pull request #24
Opened 2024-07-27 14:11 UTC by MahtaMirzaei

Related: #6

2024-07-28 14:27 UTC, fatemeh-ra requested changes

2024-07-28 14:27 UTC, fatemeh-ra commented on Mahta/TS/TS-basics/basics.ts
> +      return "tail";
define an enum for return type of the function

2024-07-28 14:27 UTC, fatemeh-ra commented on Mahta/TS/TS-basics/basics.ts
> +function power2(x: number): number {
return type of power2 should be bigint

2024-07-28 14:27 UTC, fatemeh-ra commented on Mahta/TS/TS-basics/basics.ts
> +  const capitalizedFirstName = firstName.replace(firstName.charAt(0), firstName.charAt(0).toUpperCase());
also use lower case function for the rest of characters

2024-07-28 14:27 UTC, fatemeh-ra commented on Mahta/TS/TS-basics/basics.ts
> +function callFuncNTimes(func: Function, n: number, ...funcParams: any[]): void {
our function doesn't have any input parameters.  
try this with flipACoin as input.

2024-07-28 14:27 UTC, fatemeh-ra commented on Mahta/TS/TS-basics/basics.ts
> +function callPropInObj(object: any, propertyName: string): void {
don't use any here. It is meant to be a generic type function.

2024-07-28 14:27 UTC, fatemeh-ra commented on Mahta/TS/TS-basics/basics.ts
> +  let fruits: string[] = ['Apple', 'Orange', 'Strawberry'];
the array should be the input of the function.

2024-07-28 14:27 UTC, fatemeh-ra commented on package.json
> +{
why do you have another package.json & package-lock.json out of your directory??

2024-07-28 14:27 UTC, fatemeh-ra commented on Mahta/TS/TS-basics/.gitignore
> +package-lock.json
package-lock.json should not be ignored. it's important to use the exact same package versions at different run times.

2024-07-28 14:27 UTC, fatemeh-ra commented on node_modules/.package-lock.json
> +{
what is it exactly? how did you ignore node_mosules and include this file in your commit?

2024-07-29 13:57 UTC, MahtaMirzaei commented on package.json
> +{
one belongs to node modules. how can I fix that> should I mix them?

2024-07-29 14:06 UTC, MahtaMirzaei commented on node_modules/.package-lock.json
> +{
fixed that.

2024-07-29 14:17 UTC, MahtaMirzaei commented on package.json
> +{
found out what was wrong, removed all

2024-08-01 12:20 UTC, fatemeh-ra requested changes

2024-08-01 12:20 UTC, fatemeh-ra commented on Mahta/TS/TS-basics/basics.ts
> +  return email.endsWith("@isGmail.com");
what?? isGmail.com?

2024-08-03 11:40 UTC, merged