Writing asked functions by Axios API
ConnecMent/bank pull request #29
Opened 2024-07-31 18:38 UTC by SeyedMojtaba1

related #25

2024-08-03 11:42 UTC, fatemeh-ra requested changes

2024-08-03 11:42 UTC, fatemeh-ra commented on Seyed/API calls/main.ts
> +        const response = await axios.get(`https://jsonplaceholder.typicode.com/posts`)
use the search route

2024-08-03 11:51 UTC, fatemeh-ra requested changes

2024-08-03 11:51 UTC, fatemeh-ra commented on Seyed/API calls/main.ts
> +        const response = await axios.get(`https://jsonplaceholder.typicode.com/posts`)
write the search function using provided query parameters

2024-08-07 12:00 UTC, SeyedMojtaba1 commented on Seyed/API calls/main.ts
> +        const response = await axios.get('https://jsonplaceholder.typicode.com/posts')
I fixed it and used from query parameters.

2024-08-07 12:01 UTC, SeyedMojtaba1 commented on Seyed/API calls/main.ts
> +        const response = await axios.get('https://jsonplaceholder.typicode.com/posts')
I fixed it.

2024-08-07 12:02 UTC, SeyedMojtaba1 commented on Seyed/API calls/main.ts
> +        const response = await axios.get(`https://jsonplaceholder.typicode.com/posts`)
I fixed it based on query filters parameters.

2024-08-14 14:11 UTC, fatemeh-ra requested changes

2024-08-14 14:11 UTC, fatemeh-ra commented on Seyed/API calls/main.ts
> +        const response = await axios.get(`https://jsonplaceholder.typicode.com/posts/?id=${input.id}&?userId=${input.userId}&?body=${input.body}&?title=${input.title}`)
what if some of them were not defined? the `Query` object properties are not required.

2024-08-28 13:34 UTC, fatemeh-ra approved these changes

2024-08-28 13:34 UTC, merged