Typeorm mahta
ConnecMent/bank pull request #39
Opened 2024-08-11 16:07 UTC by MahtaMirzaei

Related: #32

2024-08-14 14:15 UTC, fatemeh-ra requested changes

2024-08-14 14:15 UTC, fatemeh-ra commented on Mahta/TS/TS-typeorm/src/entity/dataSource.ts
> +  id!: number;
why did you use `!`?

2024-08-14 14:15 UTC, fatemeh-ra commented on Mahta/TS/TS-typeorm/src/entity/dataSource.ts
> +  constructor() {
Does it need a constructor?

2024-08-14 14:15 UTC, fatemeh-ra commented on Mahta/TS/TS-typeorm/src/index.ts
> +  synchronize: true,
Remove the database and test the migrations with `synchronize: false`.

2024-12-05 07:54 UTC, mkermani144 commented
Closing as stale

2024-12-05 07:54 UTC, closed without merging