MRF / JS Factory function completed 🥇
ConnecMent/bank pull request #40
Opened 2024-08-12 17:13 UTC by Mr-MRF-Dev

related: #37

2024-08-13 10:29 UTC, mkermani144 requested changes

2024-08-13 10:29 UTC, mkermani144 commented on MRF/Js/js-37/index.js
> +      return "get method called";
These two functions are meant to call `fetch`, like ```fetch(`${baseURL}/${endpoint}`)```.

2024-08-13 10:29 UTC, mkermani144 commented on MRF/Js/js-37/index.js
> +    baseURL: baseURL,
This is not needed.

2024-08-15 07:36 UTC, mkermani144 requested changes

2024-08-15 07:36 UTC, mkermani144 commented on MRF/Js/js-37/index.js
> +function callAPI({ baseURL, endPoint }) {
It doesn't make sense to put endPoint here. With this implementation, if someone wants to `get` endpoint `x` and `post` endpoint `y` for the same base url, he/she should call the factory function twice, which totally negates the benefits of factory functions. Same applies to the class implementation.  
You always need to ask which configs or parameters are set once, and which ones need to be set per use case. In an endpoint fetching scenario, there is a high chance you never alter the base url, but request different endpoints based on use case.

2024-08-15 20:23 UTC, Mr-MRF-Dev commented on MRF/Js/js-37/index.js
> +function callAPI({ baseURL, endPoint }) {
Yes, I had also considered this. I believed creating an object for each endpoint would be more efficient than specifying the endpoint each time. after refactoring the code I think your approach is better.

2024-08-16 11:48 UTC, mkermani144 requested changes
Please sync your branch with main.

2024-08-16 19:45 UTC, mkermani144 approved these changes

2024-08-16 19:45 UTC, merged