A simple database using typeorm
ConnecMent/bank pull request #42
Opened 2024-08-23 16:32 UTC by SeyedMojtaba1

2024-08-28 13:42 UTC, fatemeh-ra requested changes

2024-08-28 13:42 UTC, fatemeh-ra commented on Seyed/TypeORM basic/dataSource.ts
> +    synchronize: true,
Remove the database and test the migrations with `synchronize: false`.

2024-08-28 13:42 UTC, fatemeh-ra commented on Seyed/TypeORM basic/index.ts
> +export default dataSource
Why?

2024-08-31 13:07 UTC, SeyedMojtaba1 commented on Seyed/TypeORM basic/dataSource.ts
> +    synchronize: true,
Ok sure.

2024-08-31 14:57 UTC, SeyedMojtaba1 commented on Seyed/TypeORM basic/index.ts
> +export default dataSource
I removed it.

2024-09-02 14:14 UTC, fatemeh-ra commented on Seyed/TypeORM basic/index.ts
> +export default dataSource
not removed

2024-09-22 07:53 UTC, merged