Implementing basic CRUD oprations
ConnecMent/bank pull request #43
Opened 2024-09-02 08:00 UTC by SeyedMojtaba1

2024-09-02 14:27 UTC, fatemeh-ra requested changes

2024-09-02 14:27 UTC, fatemeh-ra commented on Seyed/TypeORM CRUD/index2.ts
> +        await repo.save(newUser);
what about code indents?  
Try using insert operator when you know it's a new row. Search for differences between save and insert queries in typeorm.

2024-09-02 14:27 UTC, fatemeh-ra commented on Seyed/TypeORM CRUD/index2.ts
> +export default dataSource
why??

2024-09-02 14:27 UTC, fatemeh-ra commented on Seyed/TypeORM CRUD/index2.ts
> +            const user = await repo.findOne({
why did you find the user? Too many queries for a simple delete operation.

2024-09-04 13:39 UTC, SeyedMojtaba1 commented on Seyed/TypeORM CRUD/index2.ts
> +export default dataSource
I fixed it.

2024-09-04 13:39 UTC, SeyedMojtaba1 commented on Seyed/TypeORM CRUD/index2.ts
> +            const user = await repo.findOne({
I fixed it.

2024-09-22 07:58 UTC, fatemeh-ra approved these changes

2024-09-22 07:59 UTC, merged