make simple pino logging
ConnecMent/bank pull request #44
Opened 2024-09-07 15:46 UTC by raminLgh

2024-09-08 07:25 UTC, mkermani144 requested changes
Please add `node_modules` to `.gitignore`.

2024-09-10 10:02 UTC, mkermani144 requested changes
Please relate the issue in the description. In addition, read the issue description carefully; it includes links to the tools that are needed for completing the task. Current log rotation implementation is done manually which is not what is not the best way to do it.

2024-09-14 07:37 UTC, mkermani144 requested changes
1. I get the following error when I run your code:
```
Error: 1h is neither a supported frequency or a number of milliseconds
```
2. Please put all these code in a log folder, so you can add code related to other tasks in the future.

2024-09-22 13:26 UTC, mkermani144 requested changes
I'm getting this error:
```
Error: No file name provided
```

2024-09-22 17:24 UTC, raminLgh commented
are you sure ? I test it now and work for me
can you delete log file and run again ?

2024-09-22 18:52 UTC, mkermani144 commented
> are you sure ? I test it now and work for me can you delete log file and run again ?

Yes, I'm sure. I tried removing log file, too.

2024-09-30 05:21 UTC, mkermani144 requested changes

2024-09-30 05:21 UTC, mkermani144 commented on ramin/log/logService.js
> +      { target: 'pino/file', options: { destination: './logfile'}}
We meant to use `pino-roll`. What happened to it?  
As you suggested in our meeting, `ping` function doesn't care about the passed `rollStream`, it just ignores it.

2024-10-03 08:15 UTC, mkermani144 approved these changes

2024-10-03 08:16 UTC, merged